# Generated by Django 5.2.8 on 2025-11-09 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checker", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="disease",
            name="info_link",
            field=models.URLField(
                blank=True, help_text="Link to learn more about this disease"
            ),
        ),
        migrations.AlterField(
            model_name="disease",
            name="symptoms",
            field=models.ManyToManyField(related_name="diseases", to="checker.symptom"),
        ),
    ]
