# Generated by Django 5.2.8 on 2025-11-13 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checker", "0002_disease_info_link_alter_disease_symptoms"),
    ]

    operations = [
        migrations.AlterField(
            model_name="disease",
            name="description",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="disease",
            name="info_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="disease",
            name="name",
            field=models.CharField(max_length=100),
        ),
    ]
