# Generated by Django 5.2.8 on 2025-11-13 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("checker", "0003_alter_disease_description_alter_disease_info_link_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rating", models.IntegerField()),
                ("message", models.TextField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
